### ISSUE TITLE
After sometime mail-notifier is not checking emails

### ISSUE THREAD

**Issue by jarbaspsf** [jcreigno/nodejs-mail-notifier#5] opened 2014-02-24 19:13 UTC
In five or ten minutes after run the script mail-notifier does not check any new emails

**Comment by Shrutichhatbar** [comment] 2015-12-01 20:07
Is it resolved?

**Comment by Shrutichhatbar** [comment] 2015-12-01 20:08
I am using mail-listenter2 and facing problems so was thinking to switch to mail notifier?

**Comment by ZuzooVn** [comment] 2015-12-23 10:38
@Shrutichhatbar : Did you find the solution?

**Comment by jcreigno** [comment] 2015-12-30 19:36
It's not a bug, the server is closing the connection 

```
imap <= '* BYE Session expired, please login again.'
```
You need to restart when you get a `end` event 

```js
var n = notifier(imap);
n.on('end', function () { // session closed
  n.start();
}).on('mail',function(m){
    console.log(m.from[0].address, m.subject);
}).start();

```

**Comment by bcompagnat** [comment] 2016-02-16 16:21
This helped me a lot, can you please put more information on the documentation about this because its not intuitive to use .on('end') with the actual doc.

**Comment by KrisSiegel** [comment] 2016-02-27 06:05
Just ran across this issue and @jcreigno's comment was very helpful. :+1:

**Comment by jcreigno** [comment] 2016-02-27 21:35
I've added the code sample to the readme to explain how to restart after an `end` event.

**Closed by jcreigno** 2016-02-27 21:35 UTC
